routes/admin.php
<?php

use App\Http\Controllers\Task\AuthorizationController;
use App\Http\Controllers\Task\BoardController;
use App\Http\Controllers\Task\PurchaseController;

//
Route::controller(PurchaseController::class)->prefix('purchases')->name('admin.')->group(function () {
    Route::get('index', 'index')->name('purchase');
    Route::get('mockapi', 'mockapi')->name('mockapi');
});

//
Route::controller(AuthorizationController::class)->prefix('authorization')->name('admin.')->group(function () {
    Route::get('index', 'index')->name('authorization');
    Route::get('connect', 'connect')->name('connect');
});

//
Route::controller(BoardController::class)->prefix('board')->name('admin.')->group(function () {
    Route::get('index', 'index')->name('board');
    Route::post('create', 'create')->name('create');
    Route::get('list', 'list')->name('list');
    Route::post('update', 'update')->name('update');
    Route::post('delete', 'delete')->name('delete');
    Route::get('viewlist', 'viewlist')->name('viewlist');
    Route::get('boardlist', 'boardlist')->name('boardlist');
    Route::get('cardlist', 'cardlist')->name('cardlist');
    Route::post('listcreate', 'listcreate')->name('listcreate');
    Route::post('cardcreate', 'cardcreate')->name('cardcreate');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('index');
});

app/Models/Task/Purchases.php
<?php

namespace App\Models\Task;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class purchases extends Model
{
    use HasFactory;
    protected $guarden = ['id'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Task/AuthorizationController.php
<?php

namespace App\Http\Controllers\Task;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Session;

class AuthorizationController extends Controller
{
    public function index()
    {
        return view('authorization');
    }

    public function connect(Request $req)
    {
        $url = "https://api.trello.com/1/members/me/?key=$req->key&token=$req->token";
        $data =  Http::get($url)->object();
        Session::put('organization', $data);
        return $data;
    }
}

app/Http/Controllers/Task/BoardController.php
<?php

namespace App\Http\Controllers\Task;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class BoardController extends Controller
{

    public function index()
    {
        return view('board');
    }

    public function create(Request $req)
    {
        $message = '';
        $req->validate([
            'name' => 'required|between:1,16384',
            'desc' => 'required|between:0,16384',
        ]);
        
        if ($req->id == null) {
            $url = "https://api.trello.com/1/boards/?name=$req->name&desc=$req->desc&key=$req->key&token=$req->token";
            $message = Http::post($url)->successful();
        } else {
            $url = "https://api.trello.com/1/boards/$req->id?name=$req->name&desc=$req->desc&key=$req->key&token=$req->token";
            $message = Http::put($url)->successful();
        }

        return response()->json([
            'message' => $message,
        ]);
    }

    public function list(Request $req)
    {
        $url = "https://api.trello.com/1/members/me/boards?key=$req->key&token=$req->token";
        return Http::get($url)->object();
    }

    public function update(Request $req)
    {
        $url = "https://api.trello.com/1/boards/$req->id?name=$req->name&desc=$req->desc&key=$req->key&token=$req->token";
        return Http::put($url);
    }
    public function delete(Request $req)
    {
        $url = "https://api.trello.com/1/boards/$req->id?key=$req->key&token=$req->token";
        return Http::delete($url);
    }
    public function viewlist(Request $req)
    {
        $url = "https://api.trello.com/1/boards/$req->id/lists?key=$req->key&token=$req->token";
        return Http::get($url)->object();
    }
    public function boardlist()
    {
        return view('boardlist');
    }
    public function cardlist(Request $req)
    {
        $url = "https://api.trello.com/1/lists/$req->id/cards?key=$req->key&token=$req->token";
        return Http::get($url)->object();
    }
    public function listcreate(Request $req)
    {
        $url = "https://api.trello.com/1/boards/$req->id/lists?name=$req->name&key=$req->key&token=$req->token";
        return Http::post($url)->object();
    }
    //
    public function cardcreate(Request $req)
    {
        $url = "https://api.trello.com/1/cards?idList=$req->id&name=$req->name&desc=$req->desc&key=$req->key&token=$req->token";
        return Http::post($url)->object();
    }
}

app/Http/Controllers/Task/PurchaseController.php
<?php

namespace App\Http\Controllers\Task;

use Illuminate\Support\Facades\Http;
use App\Http\Controllers\Controller;
use App\Models\Task\Purchases;
use Illuminate\Http\Request;

class PurchaseController extends Controller
{
    public function index()
    {
        return view('task1');
    }

    public function mockapi()
    {
        $request = Http::get('https://raw.githubusercontent.com/Bit-Code-Technologies/mockapi/main/purchase.json')->object();

        foreach ($request as $result) {
            $value = new Purchases();
            $duplicate = Purchases::where('product_name', $result->product_name)->first();
            if (empty($duplicate)) {
                $value->name = $result->name;
                $value->order_no = $result->order_no;
                $value->user_phone = $result->user_phone;
                $value->product_code = $result->product_code;
                $value->product_name = $result->product_name;
                $value->product_price = $result->product_price ?? 0.00;
                $value->purchase_quantity = $result->purchase_quantity ?? 0;
                $value->save();
            }
        }
        return Purchases::orderby('purchase_quantity', 'desc')->get();
    }
}

resources/views/authorization.blade.php
<!-- <html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="row"> -->
<div class="col-4">
</div>
<div class="col-4 mt-1">
    <div class="mb-3">
        <label for="apikey" class="form-label">Api key</label>
        <input type="text" value="2a04da80140282f2d8cb50a09e637aeb" class="form-control form-control-sm" id="apikey">
    </div>
    <div class="mb-3">
        <label for="apisecret" class="form-label">Api Secret</label>
        <input type="text" value="1929181273253c68a6dc5691d3ffa245bc30811997127c088984922ad65ce944" class="form-control form-control-sm" id="apisecret">
    </div>
    <button type="button" id="authorize" onclick="authorize()" class="btn btn-sm btn-primary">Authorize</button>
</div>
<div class="col-4">
</div>
<!-- </div>
</body> -->
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script>
    function authorize() {
        let key = $("#apikey").val();
        let token = $("#apisecret").val();
        if (key) {
            if (token) {
                $.ajax({
                    type: "get",
                    url: "{{route('admin.connect')}}",
                    data: {
                        _token: "{{csrf_token()}}",
                        key: key,
                        token: token
                    },
                    success: function(data) {
                        console.log("Data : ", data);
                        var options = "";
                        options += "<option selected id='org' value='" + data.idOrganizations[0] + "' data-id=''>" + data.initials + "</option>";
                        $('#org').html(options).trigger('change');
                        alert("Success");
                        $("#apikey").val("");
                        $("#apisecret").val("");
                    }
                });
            } else {
                alert("Input Secrate Key");
            }
        } else {
            alert("Input API Key");
        }
    }
</script>

<!-- </html> -->

resources/views/board.blade.php
<div class="col-12">
    <div class="d-flex justify-content-center bg-success fw-bold fs-5">Board Create</div>
    <div class="row mt-1">
        <div class="col-1"></div>
        <div class="col-4">
            <div class="mb-3">
                <input class="form-control form-control-sm" id="bid" hidden>
                <label for="name" class="form-label" require>Name</label>
                <input type="text" value="" class="form-control form-control-sm" id="name">
            </div>
            <div class="mb-3">
                <label for="apisecret" class="form-label">Description</label>
                <textarea type="text" value="" class="form-control form-control-sm" id="description"></textarea>
            </div>
            <button type="button" id="submit" onclick="submit()" class="btn btn-sm btn-primary">Submit</button>
            <button type="button" id="clear" onclick="clear()" class="btn btn-sm btn-danger">Refresh</button>
        </div>
        <div class="col-7" id="row">
        </div>
    </div>
</div>


<!-- modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Board List</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Name</label>
                <input type="text" value="" class="form-control form-control-sm" id="name">
                <button type="button" id="submit" onclick="createlist()" class="btn btn-sm btn-primary mt-1">Submit</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div> -->

<!--  -->
<script>
    keyy = '2a04da80140282f2d8cb50a09e637aeb';
    tokenn = '1929181273253c68a6dc5691d3ffa245bc30811997127c088984922ad65ce944';
    $(document).ready(function() {
        boardList();
    });

    function submit() {
        let id = ($("#bid").val()) == "" ? null : $("#bid").val();
        let name = $("#name").val();
        let description = $("#description").val();
        if (name) {
            $.ajax({
                type: "post",
                url: "{{route('admin.create')}}",
                data: {
                    id: id,
                    name: name,
                    desc: description,
                    key: keyy,
                    token: tokenn
                },
                success: function(data) {
                    if (data) {
                        alert("Success");
                        boardList();
                        clear();
                    } else {
                        alert("Something went wrong !!")
                    }
                }
            });
        }else alert("name field can't be empty !!")
    }

    function boardList() {
        $.ajax({
            type: "get",
            url: "{{route('admin.list')}}",
            data: {
                key: keyy,
                token: tokenn
            },
            success: function(data) {
                $("#board").remove();
                $("#row").append("<div class='row row-cols-1 row-cols-md-3 g-4' id='board'>");
                for (let i = 0; i < data.length; i++) {
                    $("#board").append("<div class='col' id='col-" + (i + 1) + "'></div>");
                    $("#col-" + (i + 1)).append("<div class='card h-100' id='card-" + (i + 1) + "'></div>");
                    $("#card-" + (i + 1)).append("<div class='card-body text-center' id='cardB-" + (i + 1) + "'></div>");
                    $("#cardB-" + (i + 1)).append("<button class='btn btn-sm btn-primary' onclick='getBoardWiseList(" + (i + 1) + ")' id='id-" + (i + 1) + "' data-status='" + data[i].id + "' data-desc='" + data[i].desc + "'>" + data[i].name + "</button>");
                    $("#card-" + (i + 1)).append("<div class='card-footer text-end' id='cardf-" + (i + 1) + "'></div>");
                    $("#cardf-" + (i + 1)).append("<button type='button' class='btn btn-sm btn-primary' onclick='viewBoardList(" + (i + 1) + ")' id='vid-" + (i + 1) + "' data-vid='" + data[i].id + "'>View List</button> <button class='btn btn-sm btn-danger ml-2' onclick='deleteBoard(" + (i + 1) + ")' id='did-" + (i + 1) + "' data-did='" + data[i].id + "'><i class='fa fa-trash'></i></button>");
                }
            }
        });
    }

    rowIdx = 0;

    function setData(data) {
        for (var i = 0; i < data.length; i++) {
            $('#boardtable').append(`<tr id="R${++rowIdx}">
                <td class="row-index text-left" id='name-${rowIdx}'}"></td>
                <td class="row-index text-left"  id='des-${rowIdx}'">${data[i].student_name}</td>
                <td class="row-index text-center" id=""><i class='fa fa-edit text-info' onclick="setForEdit(this)"></i></td>
            </tr>`);
        }
        rowIdx = 0;
    }

    function getBoardWiseList(id) {
        let bid = $("#id-" + id).attr('data-status');
        let bname = $("#id-" + id).text();
        let bdesc = $("#id-" + id).attr('data-desc');

        $("#bid").val(bid);
        $("#name").val(bname);
        $("#description").val(bdesc);
    }

    function deleteBoard(id) {
        if (confirm('Are you sure to delete???')) {
            let bid = $("#did-" + id).attr('data-did');
            $.ajax({
                type: "post",
                url: "{{route('admin.delete')}}",
                data: {
                    id: bid,
                    key: keyy,
                    token: tokenn
                },
                success: function(data) {
                    boardList();
                    clear();
                }
            });
        }
    }

    function viewBoardList(id) {
        let vid = $("#vid-" + id).attr('data-vid');
        $.ajax({
            type: "get",
            url: "{{route('admin.viewlist')}}",
            data: {
                id: vid,
                key: keyy,
                token: tokenn
            },
            success: function(data) {
                BoardList(data);
            }
        });
    }

    function BoardList(bdata) {
        $.ajax({
            type: "get",
            url: "{{route('admin.boardlist')}}",
            data: {},
            success: function(data) {
                $("#body").html(data);
                $("#board").remove();
                $("#row").append("<div class='row row-cols-1 row-cols-md-4 g-4' id='board'>");
                $("#idBoard").val(bdata[0].idBoard);
                for (let i = 0; i < bdata.length; i++) {
                    $("#board").append("<div class='col' id='col-" + (i + 1) + "'></div>");
                    $("#col-" + (i + 1)).append("<div class='card h-100' id='card-" + (i + 1) + "'></div>");
                    $("#card-" + (i + 1)).append("<div class='card-body text-center' id='cardB-" + (i + 1) + "'></div>");
                    $("#cardB-" + (i + 1)).append("<button class='btn btn-sm btn-primary' onclick='viewListwiseCard(" + (i + 1) + ")' id='cid-" + (i + 1) + "' data-list-id='" + bdata[i].id + "'>" + bdata[i].name + "</button>");
                    $("#card-" + (i + 1)).append("<div class='card-footer text-end' id='cardf-" + (i + 1) + "'></div>");
                    $("#cardf-" + (i + 1)).append("<button class='btn btn-sm btn-danger ml-2' data-bs-toggle='modal' data-bs-target='#exampleModal2' id='submit' data-list-id='" + bdata[i].id + "'><i class='fa fa-plus'></i></button>");
                }
            }
        });
    }

    function viewListwiseCard(id) {
        let cid = $("#cid-" + id).attr('data-list-id');
        console.log("cid : ", cid);
        $.ajax({
            type: "get",
            url: "{{route('admin.cardlist')}}",
            data: {
                id: cid,
                key: keyy,
                token: tokenn
            },
            success: function(data) {
                $("#crow").remove();
                $("#cardlist").remove();

                $("#list").append("<div class='row' id='crow'></div>");
                $("#list").append("<div class='row row-cols-1 row-cols-md-4 g-4' id='cardlist'>");
                $("#crow").append("<div class='col text-center' id='celem'></div>");
                $("#celem").append("<h1 class='col text-center' id='celem'>Card List</h1>");
                if (data.length > 0) {
                    for (let i = 0; i < data.length; i++) {
                        $("#cardlist").append("<div class='col' id='ccol-" + (i + 1) + "'></div>");
                        $("#ccol-" + (i + 1)).append("<div class='card h-100' id='ccard-" + (i + 1) + "'></div>");
                        $("#ccard-" + (i + 1)).append("<div class='card-body text-center' id='ccardB-" + (i + 1) + "'></div>");
                        $("#ccardB-" + (i + 1)).append("<button class='btn btn-sm btn-primary' onclick='viewListwiseCard(" + (i + 1) + ")' id='ccid-" + (i + 1) + "' data-list-cid='" + data[i].id + "'>" + data[i].name + "</button>");

                        // $("#ccardB-" + (i + 1)).append("<div class='card-footer text-end' id='cardff-" + (i + 1) + "'></div>");
                        // $("#cardff-" + (i + 1)).append("<button class='btn btn-sm btn-danger ml-2' onclick='showHiddenItem()' data-bs-toggle='modal' data-bs-target='#exampleModal2' data-list-id='" + data[i].idList + "'><i class='fa fa-plus'></i></button>");
                    }
                }
            }
        });
    }

    function clear() {
        $("#bid").val("");
        $("#name").val("");
        $("#description").val("");
    }
</script>

resources/views/boardlist.blade.php
<div class="row">
    <div class="d-flex justify-content-between bg-success">
        <!-- <input type="text" value="" class="form-control form-control-sm" id="idBoard" hidden> -->
        <div class="p-2 fw-bold">Create List</div>
        <div class="p-2">
            <button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal3">Create</button>
        </div>
    </div>
</div>
<div class="col-12 mt-1" id="row">
</div>
<div class="col-12" id="list">
</div>

<!-- modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Board List</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Name</label>
                <input type="text" value="" class="form-control form-control-sm" id="name">
                <button type="button" id="submit" onclick="submit()" class="btn btn-sm btn-primary mt-1">Submit</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- modal 2 -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Board List</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Name</label>
                <input type="text" value="" class="form-control form-control-sm" id="name2">
                <textarea type="text" value="" class="form-control form-control-sm mt-1" id="description2"></textarea>
                <button type="button" id="submit" onclick="save()" class="btn btn-sm btn-primary mt-1">Submit</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- modal 3 -->
<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Board List</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Name</label>
                <input type="text" value="" class="form-control form-control-sm" id="idBoard" hidden>
                <input type="text" value="" class="form-control form-control-sm" id="name3">
                <button type="button" id="submit" onclick="submit()" class="btn btn-sm btn-primary mt-1">Submit</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function submit() {
        // let bid = $("#submit").attr('data-list-id');
        let bid = $("#idBoard").val();
        let name = $("#name3").val();

        if (name) {
            $.ajax({
                type: "post",
                url: "{{route('admin.listcreate')}}",
                data: {
                    id: bid,
                    name: name,
                    key: keyy,
                    token: tokenn
                },
                success: function(data) {
                    console.log("data : ", data);
                    // alert("Success")
                }
            });
        } else alert("name field is required !!");


    }

    function save() {
        let bid = $("#submit").attr('data-list-id');
        let name = $("#name2").val();
        let description = $("#description2").val();
        if (name) {
            $.ajax({
                type: "post",
                url: "{{route('admin.cardcreate')}}",
                data: {
                    id: bid,
                    name: name,
                    desc: description,
                    key: keyy,
                    token: tokenn
                },
                success: function(data) {
                    console.log("data : ", data);
                    // alert("Success")
                }
            });
        } else alert("name field is required !!");

    }

    // function showHiddenItem() {
    //     $("#description").show();
    // }

    // function hideitem() {
    //     $("#description").hide();
    // }
</script>

resources/views/index.blade.php
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title></title>

    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/font-awesome.min.css')}}"> --}}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    </head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Trello</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="getPurchasePage()">Purchases</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="getAuthorizationPage()">Authorization</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="getBoardPage()">Board</a>
                    </li>
                </ul>
                <div class="">
                    <select class="form-select" id="org">
                        <!-- <option selected>Open this select menu</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option> -->
                    </select>
                </div>
            </div>
        </div>
    </nav>
    <div class="class=container-fluid">
        <div class="row" id="body"></div>
    </div>
</body>
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    function getPurchasePage() {
        $.ajax({
            type: "get",
            url: "{{route('admin.purchase')}}",
            data: {},
            success: function(data) {
                $("#body").html(data);
            }
        });
    }

    function getAuthorizationPage() {
        $.ajax({
            type: "get",
            url: "{{route('admin.authorization')}}",
            data: {},
            success: function(data) {
                $("#body").html(data);
            }
        });
    }

    function getBoardPage() {
        $.ajax({
            type: "get",
            url: "{{route('admin.board')}}",
            data: {},
            success: function(data) {
                $("#body").html();
                $("#body").html(data);
            }
        });
    }
</script>

</html>

resources/views/task1.blade.php
<!-- <html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body> -->
<!-- <div class="mt-1"> -->
<div class="col-4">

</div>
<div class="col-4 text-center">
    <button type="button" id="btnGenerate" class="btn btn-sm btn-danger pull-right mt-1" onclick="generate()">Generate Report</button>
</div>
<div class="col-4">

</div>
<!-- </div> -->
<table class="table table-bordered mt-1" id="tab">
    <thead class="table-dark">
        <th>Product Name</th>
        <th>Customer Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
    </thead>
    <tbody id="datatable">
    </tbody>
    <tfoot>
        <tr>
            <th class="text-end" colspan="2">Gross Total :: </th>
            <td id="tQty"></td>
            <td id="tTprice"></td>
            <td id="tGross"></td>
        </tr>
    </tfoot>
</table>
<!-- </body> -->
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script>
    function generate() {
        $.ajax({
            type: "get",
            url: "{{route('admin.mockapi')}}",
            data: {},
            success: function(data) {
                $("#datatable").empty();
                setData(data);
            }
        });
    }

    function setData(data) {
        let tqty = 0;
        let tTprice = 0.00;
        let tGross = 0.00;
        // let length = $("#datatable").length;
        for (var i = 0; i < data.length; i++) {
            tqty += data[i].purchase_quantity;
            tTprice += data[i].product_price;
            tGross += data[i].purchase_quantity * data[i].product_price;
            $('#datatable').append(
                `<tr>
                <td class="row-index">${data[i].product_name}</td>
                <td class="row-index">${data[i].name}</td>
                <td class="row-index">${data[i].purchase_quantity}</td>
                <td class="row-index">${data[i].product_price}</td>
                <td class="row-index">${data[i].purchase_quantity*data[i].product_price}</td>
            </tr>`);
        }

        $("#tQty").text(tqty);
        $("#tTprice").text(tTprice);
        $("#tGross").text(tGross);
    }
</script>

<!-- </html> -->